### ISSUE TITLE
Export crash

### ISSUE THREAD

**Issue by gibranlp** [phase1geo/Minder#189]
Hi,

i have been crashing a lot, when exporting to Freeplane or Freemind, if the map is a bit large just crashes, you can export tiny ones.

**Comment by phase1geo** [comment]
Any chance you could email me a minder file that crashes when exporting?

**Comment by gibranlp** [comment]
Done, you must have a mail from gibran@gibranlp.dev

Cheers

**Comment by phase1geo** [comment]
I received the email. The issue is a code issue with calculating the connection color. I have it fixed in my repository currently though it is not available through GitHub yet.

Are you using version 1.9.1 or are you using the devel branch?

**Comment by phase1geo** [comment]
I have merged the change into the master branch. It will be generally available in the next stable release.

**Comment by gibranlp** [comment]
Yes, i am using 1.9.1 actually in elementary and arch, and i have just checked the error on both.

Thanks man
Cheers

**Comment by grahamgill** [comment]
> I have merged the change into the master branch. It will be generally available in the next stable release.

Looking forward to the fix for this too. FreeMind and FreePlane exports crash Minder. By the way, I don't see the change in master, did you mean devel? 

After pointing Arch User Repository PKGBUILD to devel branch (by default the minder-git package pulls in master) and building, I still get a crash on exporting to FreeMind, but can export to FreePlane and open again in Minder.

Looks like everything is there but nodes come up all overlapping (see screenshot) so I have to move them apart manually. That's fine, but is there a keyboard shortcut that will space nodes so there are no overlaps? - can't find one in the shortcuts cheatsheet.

![image](https://user-images.githubusercontent.com/47540120/89669248-1fa3ed00-d8ad-11ea-8721-cfea1940c1ef.png)

**Comment by phase1geo** [comment]
For the overlaps, there isn’t a single button to fix the issue; however, you could try changing the layout to manual and then to horizontal.

**Comment by phase1geo** [comment]
Looking at the diagram, it appears there is more than one root node. You may need to manually move the second root node so that it’s tree is not overlapping with the first tree.

**Comment by grahamgill** [comment]
Thanks. Yes multiple root nodes. Anyway that was just an aside from seeing how the export to FreePlane and import back worked. My original Minder diagram is still good.

**Comment by phase1geo** [comment]
Is there any way that you could email me a mind map that causes the crash?

**Comment by grahamgill** [comment]
> Is there any way that you could email me a mind map that causes the crash?

Sent

**Comment by phase1geo** [comment]
I have fixed the application crash with Freemind in the master branch. I have also moved the Freeplane fix into the master branch as well.

**Comment by gibranlp** [comment]
Do you know, when the next update will be, or how can i use the devel branch, for some readon i can't paste anything on any map

**Comment by phase1geo** [comment]
I would avoid using the devel branch for now.  It will be a while before the next planned release will be made; however, I could generate a release (1.9.2) that basically contains a couple of fixes, including this one.  I'm not seeing any issues with copy/paste in the latest master branch.

What are you attempting to paste?

**Comment by gibranlp** [comment]
Sweet , thanks.

**Comment by phase1geo** [comment]
The 1.9.2 stable release is now available in GitHub with this change.

**Comment by gibranlp** [comment]
Great, i can paste and export now, thanks man you're great!

**Comment by grahamgill** [comment]
Great, thanks for the update. Export to FreeMind and FreePlane and reimport
to Minder work, and the overlapping root node problem is gone with the
vertical "listing" of the roots on import.

*Graham Gill *

Financial Engineer | d1g1t Inc.

M: +1 416-809-0890 | d1g1t.com <https://www.d1g1t.com/>



Enterprise wealth management powered by advanced analytics


*This email, including any attachments, may contain confidential and/or
privileged information. If you are not the intended recipient, or have
received this email in error, please notify the sender immediately by
returning the email and then delete this email. Do not open any
attachments. Any dissemination or use of this information by a person other
than the intended recipient is unauthorized and may be illegal.*
