### ISSUE TITLE
Wrong start and end points of connections 

### ISSUE THREAD

**Issue by jeancf** [phase1geo/Minder#71]
First of all, let me tell you that I love minder. For me it has the right balance of features, eye candy, flexibility and simplicity. Great job, pleas keep up with it!

One annoying issue that I encountered is that, depending on where nodes are located in the viewport, connections are linking the wrong sides of the nodes. see below for an example.

When the affected nodes are in the lower third of the viewport, the connection looks like this:
![Screenshot_20190617_170501](https://user-images.githubusercontent.com/885845/59615346-a1254280-9122-11e9-8e68-866f18158099.png)

If I slide the nodes towards the center of the viewport, I get this:
![Screenshot_20190617_170533](https://user-images.githubusercontent.com/885845/59615348-a1254280-9122-11e9-9076-20f9e94cea8e.png)

And when I slide them further up to the top third of the viewport I get this:
![Screenshot_20190617_170628](https://user-images.githubusercontent.com/885845/59615350-a1bdd900-9122-11e9-816b-8d6ea6836bd1.png)

This is quite annoying as the issue is present in the exports as well and it is therefore near impossible to obtain a clean finish result.

**Comment by phase1geo** [comment]
I believe that this issue is fixed in one of the development branches and will be available in the upcoming 1.4.0 release which should be available by the end of the month. If that is not an acceptable time frame, I could attempt to pull the fix out of its current branch, get it applied to the master branch sooner, and create a 1.3.2 branch.

**Comment by jeancf** [comment]
Oh great! No need to speed up for me, end of the month is fine. Thanks.

**Comment by phase1geo** [comment]
Closing bug now that 1.4.0 is in the release pipeline.

**Comment by jeancf** [comment]
I just updated Minder pulling from master and I am still experiencing the issue. Is master at 1.4.0?

**Comment by jeancf** [comment]
@phase1geo I just updated to the latest version of the master branch but I am still experiencing this problem.

![Screenshot_20190715_211203](https://user-images.githubusercontent.com/885845/61242271-91127a00-a745-11e9-98c2-7fbd42807ebe.png)
